# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  sjtu-canvas-helper = {
    pname = "sjtu-canvas-helper";
    version = "1.3.24";
    src = fetchurl {
      url = "https://github.com/Okabe-Rintarou-0/SJTU-Canvas-Helper/releases/download/app-v1.3.24/sjtu-canvas-helper_1.3.24_amd64.deb";
      sha256 = "sha256-aaQ5/KXRHGjcUSaufn+3LoWYfFLfnB/MvM9HzhF8144=";
    };
  };
}
