name: "Build & Push to Cachix"
on:
  push:
    branches:
    - master
  schedule:
    # build every Monday at 2:30
    - cron: "30 2 * * 1"

permissions: {}

jobs:
  tests:
    strategy:
      matrix:
        nurRepo:
          - definfo
        include:
          - os: macos-latest
          - os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
      pull-requests: write
    env:
      CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Install nix
        uses: nixbuild/nix-quick-install-action@2c9db80fb984ceb1bcaa77cdda3fdf8cfba92035 # v34
        with:
          nix_conf: |
            extra-substituters = https://definfo.cachix.org https://cache.garnix.io
            extra-trusted-public-keys = definfo.cachix.org-1:3xEHcK5UZeKih42Oiuo7ypfw4i0ghc9pO9DZf3M8iaY= cache.garnix.io:CTFPyKSLcx5RMJKfLo5EEPUObbA78b0YQ2DTCJXqr9g=
      - name: Build nix packages
        run: |
          nix run nixpkgs#nix-fast-build -- \
            --skip-cached \
            --no-nom \
            --cachix-cache '${{ matrix.nurRepo }}' \
            --flake ".#legacyPackages.$(nix eval --raw --impure --expr builtins.currentSystem)"
      - name: Trigger NUR update
        # Don't replace <YOUR_REPO_NAME> here!
        if: ${{ matrix.nurRepo != '<YOUR_REPO_NAME>' }}
        run: curl -XPOST "https://nur-update.nix-community.org/update?repo=${{ matrix.nurRepo }}"
