name: "Build & Push to Cachix"
on:
  push:
    branches:
    - master
  schedule:
    # build every Monday at 2:30
    - cron: "30 2 * * 1"

permissions: {}

jobs:
  tests:
    strategy:
      matrix:
        nurRepo:
          - definfo
        include:
          - os: macos-latest
          - os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
      pull-requests: write
    env:
      CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Install nix
        uses: nixbuild/nix-quick-install-action@63ca48f939ee3b8d835f4126562537df0fee5b91 # v32
      - name: Build nix packages
        run: |
          nix run nixpkgs#nix-fast-build -- --no-nom \
            --skip-cached \
            --flake ".#legacyPackages.$(nix eval --raw --impure --expr builtins.currentSystem)" \
            --cachix-cache '${{ matrix.nurRepo }}'
      - name: Trigger NUR update
        # Don't replace <YOUR_REPO_NAME> here!
        if: ${{ matrix.nurRepo != '<YOUR_REPO_NAME>' }}
        run: curl -XPOST "https://nur-update.nix-community.org/update?repo=${{ matrix.nurRepo }}"
